### ISSUE TITLE
Reporting point map doesn't scale vertically with the browser window

### ISSUE THREAD

**Issue by oxapentane** [tlm-solutions/kindergarten#7]
see screenshot

![image](https://user-images.githubusercontent.com/1297357/235415453-816bfd1a-2f1c-412b-88ef-21c71350f1f3.png)

**Comment by MarcelCoding** [comment]
Yeah, that's currently quick and dirty without any CSS :D

**Comment by MarcelCoding** [comment]
done in latest commits, theoretically on broken
